### ISSUE TITLE
Compilation error on Win10/WSL platform

### ISSUE THREAD

**Issue by djipi** [boricj/ghidra-delinker-extension#3]
Got the error when using "gradle buildExtension" on Win10/WSL.

FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/c/Projects/Ghidra/ghidra-delinker-extension/build.gradle' line: 33

* What went wrong:
An exception occurred applying plugin request [id: 'com.diffplug.spotless', version: '6.20.0']
> Failed to apply plugin [id 'com.diffplug.spotless']
   > Spotless requires Gradle 6.1.1 or newer, this was 4.4.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by boricj** [comment]
Your Gradle version appears to be too old. Building anything Ghidra related requires at least Gradle 7.3 (https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/application.properties#L5)

I have Gradle 8.2.1 locally installed and the CI jobs use Gradle 8.3 (https://github.com/boricj/ghidra-delinker-extension/actions/runs/6487869167/job/17619119160#step:5:10).

**Comment by djipi** [comment]
Thank you for this information.

Unfortunately, Win10/WSL doesn't have a recent package.
Reading package lists... Done
Building dependency tree
Reading state information... Done
gradle is already the newest version (4.4.1-10).
0 upgraded, 0 newly installed, 0 to remove and 413 not upgraded.

Anyway, I will give a try with the gradle package for Windows.

**Comment by boricj** [comment]
I'm assuming your WSL distribution is Ubuntu 20.04 based on that `gradle` version. It should be recent enough to build this, with these caveats:

- The [`gradle`](https://packages.ubuntu.com/focal/java/gradle) packages in Debian and Ubuntu are woefully outdated and were [last updated in 2018](https://salsa.debian.org/java-team/gradle/-/commit/b8c415cbd42506d22ec91c89ff9fc98365b63396). You should [install gradle manually](https://gradle.org/install/#manually) from the official website, it's just a zip file to extract.
- Also you'll need JDK 17, which is another Ghidra requirement. Ubuntu 20.04 default JDK is JDK 11, you should install the [`openjdk-17-jdk`](https://packages.ubuntu.com/focal/java/openjdk-17-jdk) package and set it as the active JDK alternative with [`update-java-alternatives`](https://manpages.ubuntu.com/manpages/focal/man8/update-java-alternatives.8.html).

Building under Windows should work in theory (I've never tried it), but the test suite assumes that [`objcopy` with ELF support](https://github.com/boricj/ghidra-delinker-extension/blob/master/src/test/java/ghidra/DelinkerIntegrationTest.java#L179-L186) is installed on the system. Most of the unit tests will fail without it.

Alternatively, you can download prebuilt versions of this extension through the [releases pages](https://github.com/boricj/ghidra-delinker-extension/releases) or from the [CI builds](https://github.com/boricj/ghidra-delinker-extension/actions) if you just want to use it as-is.

You can reach me on Discord if you need (the link is on my [GitHub profile](https://github.com/boricj), leftmost column, just above the _Achievements_ heading). It will be easier to get you up to speed through instant messaging.
